### ISSUE TITLE
Add logo in menu

### ISSUE THREAD

**Issue by asantacreu** [MadBoulder/BetaLibrary#25]
Outside of the Home page we hide the logo. When this happens, the logo should appear in the menu aligned to the left.

**Comment by asantacreu** [comment]
![image](https://user-images.githubusercontent.com/34898093/64358804-6935e900-d007-11e9-8520-ed89f19c268d.png)

**Comment by asantacreu** [comment]
If there isn't enough space to show MadBoulder, then it should only show the logo.

**Comment by asantacreu** [comment]
![image](https://user-images.githubusercontent.com/34898093/64358882-8e2a5c00-d007-11e9-80e0-93a04a1f5ea1.png)

**Comment by juangallostra** [comment]
Done as per commits: Done as per commits: c0c120152ec418dd1a1aa98f87e25e11775fdabb, de7a38b6cfd9f612b68b69602d29b45b8dda5c9a and  99116dba8b1e727de8b7939a54a71f5c6dac1300 

Currently I have only added the logo to the menu, since adding the whole main header image would be a bit weird due to the current colors. I will try and make the background transparent and see how it looks.

**Comment by asantacreu** [comment]
It looks small (at least in Pc). In the drive we have some bigger logos, maybe we can use them?

Its OK not adding the whole header for now. Wll ask Carles for a transparent background version.

**Comment by juangallostra** [comment]
Done as per commit 0edf6c30e51cb9b362771856cef996e9f2940a3b
