### ISSUE TITLE
Add "Submit Video" feature

### ISSUE THREAD

**Issue by asantacreu** [MadBoulder/BetaLibrary#36]
Add "Submit Video" feature.

This feature has to be an option in the menu, before About Us.

This page will contain the usual Add/drop file. For every file it should show a form that has to be filled with Climber, Name, Zone, Grade, Sector and Additional Notes by the user.

Once the file is uploaded there should be a notification by email to aniolsantacreu_1@hotmail.com at least.

This is the main issue for this feature. It can be splitted in smaller ones once we have more information.

**Comment by juangallostra** [comment]
- [ ] Upload functionality
- [ ] "Submit video" menu entry
- [ ] Form for boulder data
- [ ] Notification mail

**Comment by juangallostra** [comment]
@asantacreu some updates on this issue. The main problem with this feature is that heroku's storage system is read-only and ephemeral. This means that we need a 3rd party storage provider to store the uploaded files. I have been exploring 3 different approaches that can make this feature work:
 
#### Approach 1: Upload files to heroku's madboulder instance and transfer them to GDrive

The idea of this approach is to upload first the file to the server where madboulder's instance is running and immediately transfer it to Google Drive before heroku deletes the uploaded file from the server.  

This approach works for small files (<200Mb) but problems arise when trying to upload larger files.  For large files, the connection is reset after a while by the server and files are not uploaded.

Since we expect to have large file uploads I think this approach has to be discarded and we have to look for other alternatives.

#### Approach 2: Upload files directly to an Amazon S3 bucket

This approach solves the previous issue by directly uploading the files to an Amazon S3 bucket without the intermediate step of uploading the file to the server where madboulder's page is hosted. There is a detailed tutorial here that specifies how this can be achieved:

https://devcenter.heroku.com/articles/s3-upload-python

There are two problems with this approach:
1. Amazon S3 storage service is **not** a free service, see the pricing here: https://aws.amazon.com/es/s3/pricing/ After 12 months of free service we would have to start paying
2. Its implementation would require a fair amount of coding.

#### Approach 3: Embed a WeTransfer plugin in the ```/upload``` section of the page

I think this is our best option. At least we can try it and see how well it works.

It is really simple to integrate and makes use of WeTransfer's free service. WeTransfer provides the option of embedding a code snippet in webpages that can be used to send files via WeTransfer. When a file is uploaded via this snippet a link to the download page is provided. We can then attach this link to the mail that will be sent to your e-mail address @asantacreu so that you can download it easily.

Another benefit is that it shows the status of the update (in %) which is a useful feedback for users. I have been testing this approach and so far it works well. It looks like the image below: 

![Selection_001](https://user-images.githubusercontent.com/9968427/70315488-fa407a00-1819-11ea-8cf6-4ed49c9d306e.png)

**Comment by juangallostra** [comment]
Current look of the upload form:

![Selection_001](https://user-images.githubusercontent.com/9968427/70328403-3e8f4280-1839-11ea-9fdf-24746db8ce79.png)

**Comment by juangallostra** [comment]
@asantacreu I think the functionality is ready and working as expected. In fact, you should have received a testing email which, a part from validating the functionality contains a new Beta. 

Maybe we can start testing it in production (http://www.madboulder.org/upload) and to see how well it works.

**Comment by asantacreu** [comment]
@juangallostra I also think approach with WeTransfer is good as they provide a cade snipped that works fine.
I received the file sent properly and tested it from the computer and works fine.

I also think that it provides the functionality requested and is ready to be used in production.

For me this issue is complete but I do have some comments for future improvement:
- Wetransfer lets you upload any number of files, but the form only accepts information for one file.
Even if we somehow we let the user fill more than one form, the hard part comes in knowing which form goes with which video.
- Message of "file sent OK" after submit is clicked.
- Force to fill some fields in the form as name or zone
- It is well thought the grade otion to be a dropdown menu, but it is hard to cover all grades.. If the video is com America the grade scale is V1, V2, V3.. Or even in the Font scale, some zones use 5/5+ and others 5a/5b/5c.. So I think its better to leave it blank and have the user write it with text.

We shall discuss them and create the appropiate issues.

**Comment by juangallostra** [comment]
@asantacreu changes merged into `master`. I agree with your points so we can create the corresponding issues. Most of them should be fairly easy to implement.

**Comment by juangallostra** [comment]
I will close this issue after we have created the rest of issues related to the upload form

**Comment by juangallostra** [comment]
Closing since the main functionality is working, derived issues and PRs listed below:
Related issues: #55 #56 #58 
Related PR: #57
