### ISSUE TITLE
Investigate making the domain secure with https

### ISSUE THREAD

**Issue by asantacreu** [MadBoulder/BetaLibrary#43]
Investigate making the domain secure with https

**Comment by juangallostra** [comment]
@asantacreu this doesn't seem to be possible with heroku's free tier. It is a paid option, which we aren't currently using.

![Selection_002](https://user-images.githubusercontent.com/9968427/68549257-94b5c500-03f6-11ea-84a8-3d541e6c842e.png)

**Comment by asantacreu** [comment]
@juangallostra How much is it? What other things could we benefit from this tier?

**Comment by juangallostra** [comment]
The basic tier is 7$ / month per dyno (and we are currently only using one dyno). The rest of benefits (such as https) are listed in the image below, which is taken from https://www.heroku.com/pricing

![tiers](https://user-images.githubusercontent.com/9968427/68694312-3b29d380-0579-11ea-8b87-f1e9b6a3acaa.PNG)

**Comment by juangallostra** [comment]
@asantacreu it seems that after changing DNS provider it is possible to access both www.madboulder.org and [madboulder.org](http://madboulder.org) via https.

See:
* https://www.madboulder.org
* https://madboulder.org

However, the connection defaults to http.

**Comment by juangallostra** [comment]
Just found the configuration setting in Cloudfare's admin panel to redirect all traffic through https (It was set to off). Now all traffic should be redirected through https. 

I have performed several tests on different browsers and I am always redirected through https so I think the issue is solved.

![sett](https://user-images.githubusercontent.com/9968427/72455179-9c149880-37c2-11ea-9dd2-c49f33ba5859.PNG)
