### ISSUE TITLE
Form may be submitted with the video still uploading

### ISSUE THREAD

**Issue by asantacreu** [MadBoulder/BetaLibrary#55]
Form may be submitted with the video still uploading or without video at all.

We should try to prevent this from happening somehow.

Idea: A Two step process? First ask to upload video and then show form.

**Comment by juangallostra** [comment]
@asantacreu with WeTransfer's snippet I am able to know if a file has been uploaded because I get the download link. However if the download link is empty I am not able to differentiate if it is because a file is being uploaded or because no file has been selected.

I think a good solution might be to check if a download link is available and, if it is not, show a general warning that covers both cases, like:

_"Please select a file or wait until the selected file has been uploaded"_

**Comment by asantacreu** [comment]
@juangallostra That sounds good!

**Comment by juangallostra** [comment]
Closed as per #57
