### ISSUE TITLE
Limit exceeded error in uploader

### ISSUE THREAD

**Issue by asantacreu** [MadBoulder/BetaLibrary#60]
![image](https://user-images.githubusercontent.com/34898093/71180539-a9e20700-2272-11ea-87b5-09b515a879bb.png)

Limit exceeded error in uploader. When I try to upload a video I get this error. Not related to size I think..

**Comment by juangallostra** [comment]
@asantacreu I think it has to do with the max. allowed number of petitions per day (but this i just a guess). I will send an email to WeTransfer's support to see what's going on.

Meanwhile I have updated the API key to get it working again and I have set it as an environment variable in the server so that it is not stored in the html of the page. In the case someone was using our key this should fix it. 

As far as I have tested it is working again, but we'll have to keep an eye on it to see if the problem arises again.

**Comment by asantacreu** [comment]
@juangallostra Yeah now it's working again but it's not reliable.. We'll see what they told us about this max.

**Comment by juangallostra** [comment]
@asantacreu I'll let you know as soon as I have an answer

**Comment by juangallostra** [comment]
@asantacreu no answer yet...

**Comment by juangallostra** [comment]
I resent them an email 3 days ago and still no answer.

**Comment by juangallostra** [comment]
@asantacreu Bad news... 😢 This is the response I got:

Hey Juan,

I'm very sorry to tell you that work on the WeTransfer API has been discontinued. This means that we can no longer help you with technical support.

You can continue to use our developers platform, but you will not be able to generate any new keys. We hope that you have enjoyed building tools to move ideas with our API. Thank you so much for being part of this journey with us!

Best Wishes,
Amy

**Comment by asantacreu** [comment]
Well, for now it seems to be working properly, and the limit is coherent. I don't know what happened last time but let's how it does not repeat..

**Comment by asantacreu** [comment]
I'll close this for now
